set(FILES
    Source/Tools/GenAIFrameworkEditorModule.cpp
    Source/UI/GenAIFrameworkWidget.cpp
    Source/UI/GenAIFrameworkWidget.h
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.cpp
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.h
    Source/UI/NewSegment.cpp
    Source/UI/NewSegment.h
    Source/UI/Segment.cpp
    Source/UI/Segment.h
    Source/UI/ServiceRequester/NewServiceRequesterSegment.cpp
    Source/UI/ServiceRequester/NewServiceRequesterSegment.h
    Source/UI/Tab.cpp
    Source/UI/Tab.h
)
