set(FILES
    Include/GenAIFramework/Communication/AIServiceProviderBus.h
    Include/GenAIFramework/Communication/AIModelAgentBus.h
    Include/GenAIFramework/Communication/AIModelRequestBus.h
    Include/GenAIFramework/GenAIFrameworkBus.h
    Include/GenAIFramework/GenAIFrameworkTypeIds.h
    Include/GenAIFramework/SystemRegistrationContext/SystemRegistrationContext.h
    Include/GenAIFramework/Feature/FeatureBase.h
    Include/GenAIFramework/Feature/ConversationBus.h
)
