set(FILES
    ../Assets/Editor/Icons/Toolbar/GenAIFramework.qrc
    ../Assets/Editor/Icons/Toolbar/AI.svg
    Source/Tools/GenAIFrameworkEditorModule.cpp
    Source/UI/AgentConfigurationWidget/AgentConfigurationWidget.cpp
    Source/UI/AgentConfigurationWidget/AgentConfigurationWidget.h
    Source/UI/AgentConfigurationWidget/NewSegment.cpp
    Source/UI/AgentConfigurationWidget/NewSegment.h
    Source/UI/AgentConfigurationWidget/Segment.cpp
    Source/UI/AgentConfigurationWidget/Segment.h
    Source/UI/AgentConfigurationWidget/Tab.cpp
    Source/UI/AgentConfigurationWidget/Tab.h
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.cpp
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.h
    Source/UI/ServiceProvider/NewServiceProviderSegment.cpp
    Source/UI/ServiceProvider/NewServiceProviderSegment.h
    Source/UI/AIChatMessage.cpp
    Source/UI/AIChatMessage.h
    Source/UI/AIChatWidget.cpp
    Source/UI/AIChatWidget.h
    Source/UI/AIChatWidget.ui
    Source/UI/AIAssistantWidget.h
    Source/UI/AIAssistantWidget.cpp
    Source/UI/AIAssistantWidget.ui
    Source/UI/NewChatWidget.cpp
    Source/UI/NewChatWidget.h
    Source/UI/NewChatWidget.ui
)
