set(FILES
    Include/GenAIFramework/AIContext.h
    Include/GenAIFramework/Communication/AIServiceProviderBus.h
    Include/GenAIFramework/Communication/AIModelRequestBus.h
    Include/GenAIFramework/GenAIFrameworkActionBus.h
    Include/GenAIFramework/GenAIFrameworkBus.h
    Include/GenAIFramework/GenAIFrameworkScriptExecutor.h
    Include/GenAIFramework/GenAIFrameworkTypeIds.h
    Include/GenAIFramework/SystemRegistrationContext/SystemRegistrationContext.h
)
