set(FILES
    ../Assets/Editor/Icons/Toolbar/GenAIFramework.qrc
    ../Assets/Editor/Icons/Toolbar/AI.svg
    Source/Tools/GenAIFrameworkEditorModule.cpp
    Source/UI/AIAssistantWidget.h
    Source/UI/AIAssistantWidget.cpp
    Source/UI/AIAssistantWidget.ui
    Source/UI/GenAIFrameworkWidget.cpp
    Source/UI/GenAIFrameworkWidget.h
    Source/UI/AIChatWidget.cpp
    Source/UI/AIChatWidget.h
    Source/UI/AIChatWidget.ui
    Source/UI/NewChatWidget.cpp
    Source/UI/NewChatWidget.h
    Source/UI/NewChatWidget.ui
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.cpp
    Source/UI/ModelConfiguration/NewModelConfigurationSegment.h
    Source/UI/NewSegment.cpp
    Source/UI/NewSegment.h
    Source/UI/Segment.cpp
    Source/UI/Segment.h
    Source/UI/ServiceProvider/NewServiceProviderSegment.cpp
    Source/UI/ServiceProvider/NewServiceProviderSegment.h
    Source/UI/Tab.cpp
    Source/UI/Tab.h
)
